#Percentage of players required to skip the night.
# Default: 50
# Range: 0 ~ 100
sleep_percent = 50
#List of messages, from which one will be shown, when a player goes to bed
#(Available parameters: %player% = Player name)
sleep_messages = ["%player% is now in bed."]
#List of messages, from which one will be shown, when a player leaves his bed
#(Available parameters: %player% = Player name)
wake_messages = ["%player% stood up."]
#List of messages, from which one will be shown, when the night was skipped
morning_messages = ["Good Morning"]
#If true, the time since last rest is reset for all players, if enough other players are successfully sleeping. So not every player has to sleep to prevent phantom spawning for him.
all_players_rest = false
#If dimension_list_type is set to SLEEP_ACTIVE, the list is the list of dimensions in which the sleep voting is active.
#If dimension_list_type is set to SLEEP_INACTIVE, the list is the list of dimensions in which the sleep voting is inactive.
dimensions = ["minecraft:overworld"]
#If dimension_list_type is set to SLEEP_ACTIVE, the dimension list is the list of dimensions in which the sleep voting is active.
#If dimension_list_type is set to SLEEP_INACTIVE, the dimension list is the list of dimensions in which the sleep voting is inactive.
#Allowed Values: SLEEP_ACTIVE, SLEEP_INACTIVE
dimension_list_type = "SLEEP_ACTIVE"
#Block names of beds being ignored for sleep percentage.
block_blacklist = []
